export const INDIA_STATE_CODES: Record<string, string> = {
  "ANDAMAN AND NICOBAR ISLANDS": "35",
  "ANDHRA PRADESH": "37",
  "ARUNACHAL PRADESH": "12",
  "ASSAM": "18",
  "BIHAR": "10",
  "CHANDIGARH": "04",
  "CHHATTISGARH": "22",
  "DADRA AND NAGAR HAVELI AND DAMAN AND DIU": "26",
  "DELHI": "07",
  "GOA": "30",
  "GUJARAT": "24",
  "HARYANA": "06",
  "HIMACHAL PRADESH": "02",
  "JAMMU AND KASHMIR": "01",
  "JHARKHAND": "20",
  "KARNATAKA": "29",
  "KERALA": "32",
  "LADAKH": "38",
  "LAKSHADWEEP": "31",
  "MADHYA PRADESH": "23",
  "MAHARASHTRA": "27",
  "MANIPUR": "14",
  "MEGHALAYA": "17",
  "MIZORAM": "15",
  "NAGALAND": "13",
  "ODISHA": "21",
  "PUDUCHERRY": "34",
  "PUNJAB": "03",
  "RAJASTHAN": "08",
  "SIKKIM": "11",
  "TAMIL NADU": "33",
  "TELANGANA": "36",
  "TRIPURA": "16",
  "UTTAR PRADESH": "09",
  "UTTARAKHAND": "05",
  "WEST BENGAL": "19",
}